name: Controller-Integration-Tests

on:
  workflow_dispatch:
  push:
    branches: ['main', 'release-*']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
  pull_request:
    branches: ['*']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  controller-integration-tests:
    name: Controller Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # ratchet:actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: Run controller integration tests
        run: make test-controller-integration
